"""empty message

Revision ID: 0f886d621f77
Revises: aa4998d1784d
Create Date: 2024-05-30 13:17:13.487874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f886d621f77'
down_revision: Union[str, None] = 'aa4998d1784d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('cutlery', sa.Integer(), nullable=True))
    op.alter_column('order', sa.Column('items', sa.ARRAY(sa.JSON), nullable=True))
    op.alter_column('user', sa.Column('favourites', sa.ARRAY(sa.Integer), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'favourites',
               existing_type=sa.ARRAY(sa.Integer()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('order', 'items',
               existing_type=sa.ARRAY(sa.JSON()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.drop_column('order', 'cutlery')
    # ### end Alembic commands ###
