"""empty message

Revision ID: 7c11b7319aca
Revises: 
Create Date: 2024-07-23 02:14:03.753135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c11b7319aca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('isPercent', sa.Boolean(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('maxUse', sa.Integer(), nullable=False),
    sa.Column('used', sa.ARRAY(sa.Integer()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'favourites',
               existing_type=sa.ARRAY(sa.Integer()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('order', 'items',
               existing_type=sa.ARRAY(sa.JSON()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.drop_table('promo')
    # ### end Alembic commands ###
