"""empty message

Revision ID: aa4998d1784d
Revises: d9ace9196d7a
Create Date: 2024-05-21 17:23:01.198232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa4998d1784d'
down_revision: Union[str, None] = 'd9ace9196d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', sa.Column('items', sa.ARRAY(sa.JSON), nullable=True))
    op.alter_column('user', sa.Column('favourites', sa.ARRAY(sa.Integer), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'favourites',
               existing_type=sa.ARRAY(sa.Integer()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('order', 'items',
               existing_type=sa.ARRAY(sa.JSON()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    # ### end Alembic commands ###
