"""empty message

Revision ID: ab60867fe525
Revises: 7c11b7319aca
Create Date: 2024-07-23 02:24:36.531102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab60867fe525'
down_revision: Union[str, None] = '7c11b7319aca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo', sa.Column('desc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'favourites',
               existing_type=sa.ARRAY(sa.Integer()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.drop_constraint(None, 'promo', type_='unique')
    op.drop_column('promo', 'desc')
    op.alter_column('order', 'items',
               existing_type=sa.ARRAY(sa.JSON()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    # ### end Alembic commands ###
